### ISSUE TITLE
Can we read a class like LearnerModelParam directly from byte array given by xgboost JNI

### ISSUE THREAD

**Issue by USCYuandaDu** [jpmml/jpmml-xgboost#26]
Hi, 
I found your code read data one by one from XGBoostDataInput which is a wrapper of a byte array.
https://github.com/jpmml/jpmml-xgboost/blob/6a557d317b3cbc64f2e8c287cf937b54a81dc888/src/main/java/org/jpmml/xgboost/Learner.java#L59-L64
My question is can we read a class like LearnerModelParam  instead of reading data one by one? 
Thank you! 
Bests,
Yuanda

**Comment by vruusmann** [comment]
The naming/structure of JPMML-XGBoost classes tries to mirror "native" XGBoost classes as closely as possible. For example, that's the reason for calling this class `Learner`, and calling its fields `base_score`, `num_features`, etc. Wouldn't want to deviate from this principle, because it makes JPMML-XGBoost/XGBoost source code mapping very easy (eg. you can find usages of `num_class` by performing simple text search).

So, JPMML-XGBoost will not have a `LearnerModelParam` class until XGBoost has it first.
