### ISSUE TITLE
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 514, Size: 486

### ISSUE THREAD

**Issue by philipus** [jpmml/jpmml-xgboost#3]
any idea?

**Comment by vruusmann** [comment]
You should paste the full stack trace here.

At the moment, you have only provided the exception message, which indicates invalid list access by _some_ component in relation to _some_ action (cannot be any specific, because there's no stack trace).

Given that you were hacking around DMatrix earlier, I would suspect that there's a conflict between the `xgboost` model object and the associated feature map (eg. mismatching number of columns).

**Comment by philipus** [comment]
i will check that

data.matrix is not the same as genDMatrix

probably i need to use your genDMatrix function

did you try it with large data sets? because in comparison with data.matrix function genDMatrix was much slower

**Comment by vruusmann** [comment]
I haven't tested the "limits" of the `genDMatrix()` function. It performs adequately with 1000 x 100 data.frame objects.

You should use the `genDMatrix()` function if your data.frame contains factor fields. The point is that a single factor field is expanded into `n` columns (where `n` is the number of factor levels), and the resulting DMatrix object is a sparse data matrix.

If you need  to work with much larger data.frame objects, then I would suggest you to rewrite the `genDMatrix()` function in some real programming language (such as Java or Python), and execute it outside of your R script.

**Comment by philipus** [comment]
can you tell me the difference between genDMatrix() in your case (uitil) and xgb.DMatrix which is probably used internaly in xgboost implementation when my input is simply a local data.frame or data.matrix???

because this implementation seems to be much faster

**Input Type: it takes several types of input data**:
Dense Matrix: R's dense matrix, i.e. matrix ;
Sparse Matrix: R's sparse matrix, i.e. Matrix::dgCMatrix ;
Data File: local data files ;
xgb.DMatrix: its own class (recommended).

**Comment by vruusmann** [comment]
The function `genDMatrix()` first exports the provided `data.frame` object into a file in local filesystem using the [LIBSVM data format](http://www.csie.ntu.edu.tw/~cjlin/libsvm/faq.html#/Q03:_Data_preparation), and then reads this file back into `xgb.DMatrix` object.

I couldn't find a way to construct a `xgb.DMatrix` object "directly" (ie. in-memory) based on some `data.frame` object. Hence the roundtrip to a temporary LIBSVM file.

The function `genDMatrix()` is slow because it is rather inefficient to generate LIBSVM file using R's string manipulation facilities. You should be able to get much better performance if you save the original `data.frame` object in CSV data format, and then perform the CSV to LIBSVM conversion using a Java or Python application.

Does the conversion work when you train the XGBoost model using a subset of your data? For example, using 1000 rows instead of all 100'000 rows?

**Comment by philipus** [comment]
I will try

Could you explain why you need this step



	for(i in 1:nrow(df_X)){
		cell_offset = (col_offset + sapply(df_X[i, ], FUN = factor2pos))
		cell_value = sapply(df_X[i, ], FUN = format_cell)

		y_value = df_y[i]
		X_values = paste(na.omit(cell_offset), na.omit(cell_value), sep = ":", collapse = " ")

		cat(paste(y_value, " ", X_values, "\n", sep = ""), file = fp)
	}

Is this for the final jpmml step important
 
The for loop is extremely slow with 2mio rows i guess

**Comment by vruusmann** [comment]
This loop prints the `data.frame` object row-by-row in LIBSVM data format to the specified file.

The LIBSVM data format is a sparse matrix representation:
```
<y> <col1_index>:<col1_value> <col2_index>:<col2_value> .. <colN_index>:<colN_value>
```

There's nothing JPMML-specific about it all. The only requirement is that your feature map and `DMatrix` object must be consistent with one another - if not, you will get an `IndexOutOfBoundsException` during conversion.
