### ISSUE TITLE
the score from json file of xgboost doesnot match with xgboost sklearn2pmml as well as the value field . why?

### ISSUE THREAD

**Issue by Ani24may** [jpmml/jpmml-xgboost#32]
![json](https://user-images.githubusercontent.com/32966484/45754581-a740ce00-bc39-11e8-963e-787308d84185.PNG)
![skl2pmml](https://user-images.githubusercontent.com/32966484/45754583-a871fb00-bc39-11e8-96d8-df4896003f73.PNG)

**Comment by Ani24may** [comment]
I have attached two files,the one is the json file that we get from xgboost model and the other is the pmml file.
My issue is why the score values are different. 
For e.g: in pmml score is "0.35819092" but if we look at the json file its "0.358190924" .

And, as well as the value field. 
For e.g: in pmml value is"76.5"  and in json file its "77".

Can you please explain me in understanding this?

**Comment by vruusmann** [comment]
> For e.g: in pmml score is "0.35819092" but if we look at the json file its "0.358190924" .

JPMML-XGBoost loads score values from the XGBoost binary dump file. As such, these are the absolutely correct values.

The string `0.35819092` is the result of formatting 32-bit floating point values suing the `java.lang.Float.toString()` method. This is the shortest string that preserves the score value as-is. If you add trailing numbers to it, then they are redundant, because they "overflow" the precision of the 32-bit floating point data type.

> in pmml value is"76.5" and in json file its "77"

The formatting depends on the feature map specification. The PMML value is formatted as `float`, whereas the JSON value is formatted as `integer`.

**Comment by Ani24may** [comment]
Thanks a lot for the clear explanantion.
