### ISSUE TITLE
Translation of Non-SKLearn Python XGB Models

### ISSUE THREAD

**Issue by Geoiv** [jpmml/jpmml-xgboost#33]
JPMML Devs,

I am relatively new to translation of models to PMML, and your project has been immensely helpful to me in my own projects. Currently, I'm in a situation where I have a Python XGB model that has already been built and trained without the use of SciKitLearn, and I need to translate it into PMML. Unfortunately, I am not able to rebuild the model using SKLearn, due to restrictions out of my control.

Any examples or guides I have found have involved sklearn2pmml and models being built from the ground up as opposed to pre-existing ones. Does any documentation or example code exist that may help me in translating this model? I am aware that this appears to be a niche situation, and under an ideal situation I would simply refactor to use SKLearn and retrain the model, but like I said I cannot. Whether this is possible or not, I very much appreciate any information you may be able to give me.

**Comment by vruusmann** [comment]
> I have a Python XGB model that has already been built and trained without the use of SciKitLearn, and I need to translate it into PMML.

This model was most likely trained using the `xgboost.train` method (https://xgboost.readthedocs.io/en/latest/python/python_api.html#xgboost.train), which returns an `xgboost.Booster` object.

If so, then you can manually create a "wrapper" `XGBClassifier` or `XGBRegressor` (depending on the objective function) object around it. One you have this wrapper estimator ready, then create a "wrapper" `PMMLPipeline` object around it, and call the `sklearn2pmml.sklearn2pmml(obj, path)` function as usual. Please note that there is no need to call the `PMMLPipeline#fit(X, y)` method, because this wrapper estimator is already in a fully fitted state.

If you know more about the features associated with the `Booster` object, then you may additionally initialize `PMMLPipeline.active_fields` and `PMMLPipeline.target_fields` attributes.

Sample code:
```Python
regressor = XGBRegressor()
regressor._Booster = xgboost.train(...)

from sklearn2pmml import make_pmml_pipeline, sklearn2pmml

pipeline = make_pmml_pipeline(regressor, active_fields = [...], target_fields = [...])
sklearn2pmml(pipeline, "XGBoost.pmml")
```

The internal state of the `XGBClassifier` object is a bit more complex, and you may need to initialize other attributes (eg. target categories information in the form of an embedded `LabelEncoder` object) in addition to the `_Booster` attribute. If the `sklearn2pmml.sklearn2pmml()` function should complain about some missing attribute, then please check XGBoost documentation/source code for more details.

**Comment by Geoiv** [comment]
Your advice got me to a milestone in my project much faster than I expected to get there. Thank you so much!
