### ISSUE TITLE
python support

### ISSUE THREAD

**Issue by marquisthunder** [jpmml/jpmml-xgboost#4]
will it be possible a python exporter port?

**Comment by vruusmann** [comment]
You mean classes `xgboost.sklearn.XGBClassifier` and `xgboost.sklearn.XGBRegressor`?

It should be pretty trivial, because these classes are wrappers around the "native" XGBoost model object, whose conversion is fully handled by the [JPMML-XGBoost] (https://github.com/jpmml/jpmml-xgboost) library.

There may be some difficulties constructing the accompanying XGBoost feature map object. Will have to check, but it's probably safe to assume that all features are 32-bit floats (ie. no integer or categorical variables).

**Comment by vruusmann** [comment]
The [JPMML-SkLearn] (https://github.com/jpmml/jpmml-sklearn) library will include support for these two estimator types early next week.

**Comment by vruusmann** [comment]
Support for `XGBClassifier` and `XGBRegressor` model types was implemented in commits https://github.com/jpmml/jpmml-sklearn/commit/4584f0a969d11e7e5afc8ab84092cd7d35988cc6 and https://github.com/jpmml/jpmml-sklearn/commit/bc022a3c6353a4eec5f377e6937237c73334c445, respectively.
