### ISSUE TITLE
New Output Tag for Classification in V1.0.3+

### ISSUE THREAD

**Issue by jtenini** [jpmml/jpmml-xgboost#5]
It seems that for binomial classification models, the output tag has changed from the usual logistic transform to a more general model stacking approach. Would you consider returning the binomial case to the original output tag? Doing so would make it feasible to support just the binomial case without having to support the entire spec.

**Comment by vruusmann** [comment]
The updated encoding is the correct one:
1. The model type is exposed as `classification` (previously `regression`).
2. The target variable is a categorical string. As with all classification-type models, it is possible to query the list of target categories (previously unavailable).
3. The model produces a categorical target field, and a list of probability-type output fields (previously, the model produced a list of numeric output fields, and you had to check their names if you wanted to distinguish between them).
4. When executed with the [JPMML-Evaluator] (https://github.com/jpmml/jpmml-evaluator) library, the target value is an instance of `org.jpmml.evaluator.HasProbabilities` (previously a `java.lang.Double`).

If you *still* feel like going back to the old encoding, then I would recommend you to create a subclass of `org.jpmml.xgboost.LogisticClassification` and customize the method `LogisticClassification#encodeMiningModel(Segmentation, float, FeatureSchema)` as needed. It shouldn't take more than ten lines of code, because you can rely on a wide variety of utility methods.

Also, you should give a serious thought about upgrading your PMML engine to support [model chains] (http://dmg.org/pmml/v4-2-1/MultipleModels.html). Going forward, it should be considerably cheaper than having to maintain a collection of dumbed-down PMML conversion tools.
