### ISSUE TITLE
Python error parsing feature map

### ISSUE THREAD

**Issue by toonvds** [jpmml/jpmml-xgboost#61]
I am having trouble parsing the feature map when using jpmml-xgboost with Python (xgboost 1.5.0).

Either I get the error: ‘IllegalArgumentException: float’ tracing back to the fromString function: https://github.com/jpmml/jpmml-xgboost/blob/44db6ab4672ab40c2e17aab3a62876ec3e37a4dc/pmml-xgboost/src/main/java/org/jpmml/xgboost/FeatureMap.java#L193
This is strange as this ‘float’ argument comes from the python function ‘to_fmap_type(dtype)’ provided in the README.md. I don't know why 'float' is not recognized as such.

Alternatively, when using the embedded feature map and omitting the ‘--fmap-input’ command, I get an error saying that this command is in fact required.

**Comment by vruusmann** [comment]
> I get the error: ‘IllegalArgumentException: float’ tracing back to the fromString function: 

But the "float" case is fully handled there:
https://github.com/jpmml/jpmml-xgboost/blob/1.6.4/pmml-xgboost/src/main/java/org/jpmml/xgboost/FeatureMap.java#L202-L203

> I don't know why 'float' is not recognized as such.

Because you're trying to execute the latest instructions (README) using an outdated JPMML-XGBoost version software.

Update to latest, and everything will be OK. Today, the minimum will be JPMML-XGBoost version 1.6.4, or SkLearn2PMML version 0.79.0 (depending on what's your preferred front-end).
