### ISSUE TITLE
Support for multi-target models

### ISSUE THREAD

**Issue by situjunhao** [jpmml/jpmml-xgboost#70]

**Comment by vruusmann** [comment]
Here's what I found while experimenting with XGBoost 2.0.2:

The `XGBRegressor.fit(X, y)` method appears to accept a multi-column `y` dataset without problems. I was expecting that this functionality must be enabled by setting some control flag first (for example, like one needs to set `enable_categorical = True` for enabling native categorical splits).

Next, the "style" of multi-target models depends on the value of the `multi_strategy` control parameter.

When this parameter is left unset (default), then the XGBoost model file appears to contain a separate tree set for each target fields. For example, when using `XGBRegressor(n_estimators = 17)`, then the XGBoost model file contains 34 trees, which obviously represent two 17-element tree sets.

When this parameter is set to the `multi_output_tree` value, then the XGBoost model file appears to contain a single tree set; the leaf nodes of each tree are multi-dimensional. For example, when using `XGBRegressor(n_estimators = 17, multi_strategy = "multi_output_tree")`, then the XGBoost model file contains 17 trees.

**Comment by vruusmann** [comment]
The latest JPMML-XGBoost library version does not accept multi-target models because of this sanity check:
https://github.com/jpmml/jpmml-xgboost/blob/1.8.1/pmml-xgboost/src/main/java/org/jpmml/xgboost/Learner.java#L354-L356

However, it should be trivial to enable multi-target support for the first model style (ie. the one where the `multi_strategy` control parameter is left unset).

The second model style would require a PMML vendor extension.
